---
# See https://github.com/jvautier/project-cli
fullname: jvautier/digitalocean-api-cli
description: DigitalOcean tiny api client
tags:
  - python
  - cli
  - digitalocean
  - api
github:
  has_issues: true
  has_projects: false
  has_wiki: false
